# Generated by Django 4.2.3 on 2023-08-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="dropdown1",
            field=models.CharField(
                choices=[
                    ("ai", "Artificial Intelligence"),
                    ("web-dev", "Web Development"),
                    ("blockchain", "Blockchain"),
                    ("testing", "Testing"),
                    ("database", "Database"),
                ],
                default="ai",
                max_length=50,
            ),
        ),
    ]
